--IMPLEMENTE UM GATILHO (TRIGGER) QUE ATUALIZE A TABELA CONTA, PARA O CAMPO SALDO_CONTA, 
--SEMPRE QUE UMA NOVA LINHA FOR INSERIDA NA TABELA DE DEPÓSITO OU EMPRÉSTIMO.

CREATE TRIGGER ATUALIZA_VALOR_EMPRESTIMO
  AFTER INSERT OR UPDATE
  ON EMPRESTIMO
  FOR EACH STATEMENT 
    EXECUTE PROCEDURE update_valor_conta(); --procedure teste
    
  
CREATE TRIGGER ATUALIZA_VALOR_DEPOSITO
  AFTER INSERT OR UPDATE
  ON DEPOSITO
  FOR EACH STATEMENT 
    EXECUTE PROCEDURE update_valor_conta(); --procedure teste
